version: "3.7"

services:
  node:
    build:
      context: .
    container_name: "backend"
    ports:
      - "3333:3333"
    volumes: 
      - ./src:/app  
    depends_on:
      - db

  db:
    image: postgres:15.5
    container_name: database_back
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gazin
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local